dev:
  host: localhost #主机
  user: root #账号
  password: "wanggeng123456" #密码 一定要字符串
  port: 3306 #端口
  database: typeorm-study # 指定连接的数据库名
  waitForConnections: true # 等待连接
  connectionLimit: 10 # 连接池的连接数限制
  queueLimit: 0 # 等待连接的最大数量，0表示无限制

prod:
  host: "db.prod.com"
  user: "prod_user"
  password: "prod_password"
  database: "prod_db"
  connectionLimit: 20
